
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://neoklosch.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: ""

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Markus Paeschke"
title: "{ Neoklosch }"
description: "Blog and website of Markus Paeschke aka Neoklosch."
keywords: "neoklosch, markus, paeschke, android"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

background-img: "../img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "Believe you can and you are halfway there."
  - text: "Work until your idol becomes your rival!"

me-img: "/img/me.png"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/favicon-36.png"
icon-48p: "/img/web-app/favicon-48.png"
icon-72p: "/img/web-app/favicon-72.png"
icon-96p: "/img/web-app/favicon-96.png"
icon-144p: "/img/web-app/favicon-144.png"
icon-192p: "/img/web-app/favicon-192.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: ""

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/motey.png"
    date: "Mai 2017"
    description: "Created the [Motey](https://github.com/Neoklosch/Motey) project"

  - image: "/img/timeline/dubsmash.png"
    date: "Mai 2016 - Mai 2017"
    description: "Android developer at Dubsmash"

  - image: "/img/timeline/pong.png"
    date: "December 2016"
    description: "Created the [Pongduino](https://github.com/Neoklosch/Pongduino) project"

  - image: "/img/timeline/ieee_big_data.png"
    date: "December 2016"
    description: "Publication at IEEE BigData 2016: [Visually Programming Dataflows for Distributed Data Analytics](http://ieeexplore.ieee.org/document/7840860/)"

  - image: "/img/timeline/crlf.jpg"
    date: "December 2015"
    description: "Created the [crlf-helper](https://github.com/Neoklosch/crlf-helper) project"

  - image: "/img/timeline/asciitableflip.png"
    date: "November 2015"
    description: "GDG DevFest Berlin 2015 - Created [AsciiTableFlip](https://github.com/kollektivpp/AsciiTableFlip) project"

  - image: "/img/timeline/medienfassade.jpg"
    date: "November 2015"
    description: "Joined GDG DevFest Berlin 2015"

  - image: "/img/timeline/db_hackathon.png"
    date: "November 2015"
    description: "3rd DB Hackathon - Created [DB API Server](https://github.com/Neoklosch/db-api-server) and [GamDBit-Server](https://github.com/Neoklosch/GamDBit-Server)"

  - image: "/img/timeline/cgm.png"
    date: "October 2015 - February 2016"
    description: "Android developer at CompuGroup Medical AG"

  - image: "/img/timeline/uqu.png"
    date: "June 2015"
    description: "Salesforce HackNWear - Created [uQu](https://github.com/Cookie-Monsters/uQu-Backend) project"

  - image: "/img/timeline/donator.png"
    date: "April 2015"
    description: "Wincor Nixdorf Hackfest - Created [Donator](http://www.wincor-nixdorf.com/internet/site_KR/DE/WincorNixdorf/Press/pressreleases/2015/hackfestd.html?nn=1251010) project"

  - image: "/img/timeline/studies.png"
    date: "October 2014 - today"
    description: "Master of Science, computer science, TU Berlin"

  - image: "/img/timeline/beatingblocks.png"
    date: "November 2014"
    description: "GDG DevFest Berlin 2014 - Created [BeatingBlocks](https://github.com/kollektivpp/BeatingBlocks) project"

  - image: "/img/timeline/devfest_2014.jpg"
    date: "November 2014"
    description: "Joined GDG DevFest Berlin 2014"

  - image: "/img/timeline/jsconf.png"
    date: "September 2014"
    description: "JSConf EU 2014"

  - image: "/img/timeline/droidcon.png"
    date: "May 2014"
    description: "Joined the droidcon Berlin"

  - image: "/img/timeline/android.jpg"
    date: "April 2013 - September 2015"
    description: "Android and web developer at SinnerSchrader Mobile"

  - image: "/img/timeline/devfest_2013.png"
    date: "November 2013"
    description: "Joined GDG DevFest Berlin 2013"

  - image: "/img/timeline/idaacs.jpg"
    date: "September 2013"
    description: "Talk about \"Interactive Media Facade Web Application with ClusterGL\" at the IDAACS’2013"

  - image: "/img/timeline/idaacs.jpg"
    date: "September 2013"
    description: "Publication at IDAACS’2013: [Interactive Media Facade Web Application with ClusterGL](http://ieeexplore.ieee.org/document/6662676/)"

  - image: "/img/timeline/vr.png"
    date: "March 2013"
    description: "Talk about \"Augmented reality - studentproject meventr\" at the 13. International Students Academic Presentation at the Yuanpei University in Taiwan"

  - image: "/img/timeline/bachelor.png"
    date: "October 2010 - August 2013"
    description: "Bachelor of Science, Applied computer science 1.8, HTW Berlin"

  - image: "/img/timeline/black-belt.jpg"
    date: "April 2006"
    description: "Becomes a black belt in Karate"

  - image: "/img/timeline/start.jpg"
    date: "November 2005"
    description: "Started coding"

# First image of the Timeline

timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "markus.paeschke@gmail.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Markus Paeschke aka Neoklosch is an awesome person. He lives in Berlin, where he works on several Anroid and web projects. In his spare time, Neoklosch likes to do sport, make youtube videos and created useless arduino projects."
author_blurb_image: "/img/author.jpg"

##################
# Social Buttons #
##################

social:
  - title: "twitter"
    url: "https://twitter.com/neoklosch"
  - title: "github"
    url: "https://github.com/neoklosch"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

err-404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

# keybase-username: johnsmith
# keybase-in-social: True
# keybase-in-footer: True

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Timeline: 'timeline'
  Contact: 'contact'
  # Blog: 'latest-post'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
